# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSAForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtInput = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(170, 90, 331, 71))
        self.txtInput.setObjectName("txtInput")
        self.txtOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.txtOutput.setGeometry(QtCore.QRect(170, 180, 331, 71))
        self.txtOutput.setReadOnly(True)
        self.txtOutput.setObjectName("txtOutput")
        self.txtPublicKey = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPublicKey.setGeometry(QtCore.QRect(160, 280, 331, 20))
        self.txtPublicKey.setReadOnly(True)
        self.txtPublicKey.setObjectName("txtPublicKey")
        self.txtPrivateKey = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPrivateKey.setGeometry(QtCore.QRect(160, 340, 331, 20))
        self.txtPrivateKey.setReadOnly(True)
        self.txtPrivateKey.setObjectName("txtPrivateKey")
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setGeometry(QtCore.QRect(100, 380, 121, 23))
        self.btnGenerate.setObjectName("btnGenerate")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(280, 380, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(430, 380, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 151, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 280, 131, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 330, 121, 31))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGenerate.setText(_translate("MainWindow", "Tạo khóa ngẫu nhiên"))
        self.btnEncrypt.setText(_translate("MainWindow", "Mã hoá"))
        self.btnDecrypt.setText(_translate("MainWindow", "Giải mã"))
        self.label.setText(_translate("MainWindow", "RSA"))
        self.label_2.setText(_translate("MainWindow", "Nhập văn bản gốc / bản mã"))
        self.label_3.setText(_translate("MainWindow", "Hiển thị kết quả"))
        self.label_4.setText(_translate("MainWindow", "Hiển thị Khóa Công Khai"))
        self.label_5.setText(_translate("MainWindow", "Hiển thị Khóa Bí Mật"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
